version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  
  kafka1:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kafka2:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: energy_db
      MYSQL_USER: energy_user
      MYSQL_PASSWORD: energy_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
  
  webserver:
    build: ./webserver
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: energy_user
      DB_PASSWORD: energy_pass
      DB_NAME: energy_db
    depends_on:
      - mysql
  
  subscriber:
    build: ./subscriber
    environment:
      KAFKA_BROKERS: kafka1:9092,kafka2:9093
      WEB_SERVER_URL: http://webserver:5000
    depends_on:
      - kafka1
      - kafka2
      - webserver


  publisher1:
    build: ./publishers/publisher1
    environment:
      KAFKA_BROKERS: kafka1:9092,kafka2:9093
      DATA_FILE: /app/data.csv
    volumes:
      - ../data/split/part_1.csv:/app/data.csv
    depends_on:
      - kafka1
      - kafka2

  publisher2:
    build: ./publishers/publisher2
    environment:
      KAFKA_BROKERS: kafka1:9092,kafka2:9093
      DATA_FILE: /app/data.csv
    volumes:
      - ../data/split/part_2.csv:/app/data.csv
    depends_on:
      - kafka1
      - kafka2

  publisher3:
    build: ./publishers/publisher3
    environment:
      KAFKA_BROKERS: kafka1:9092,kafka2:9093
      DATA_FILE: /app/data.csv
    volumes:
      - ../data/split/part_3.csv:/app/data.csv
    depends_on:
      - kafka1
      - kafka2

  publisher4:
    build: ./publishers/publisher4
    environment:
      KAFKA_BROKERS: kafka1:9092,kafka2:9093
      DATA_FILE: /app/data.csv
    volumes:
      - ../data/split/part_4.csv:/app/data.csv
    depends_on:
      - kafka1
      - kafka2

  publisher5:
    build: ./publishers/publisher5
    environment:
      KAFKA_BROKERS: kafka1:9092,kafka2:9093
      DATA_FILE: /app/data.csv
    volumes:
      - ../data/split/part_5.csv:/app/data.csv
    depends_on:
      - kafka1
      - kafka2

volumes:
  mysql_data: